# Generated by Django 4.2.25 on 2025-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='seo_description',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='tagline',
            new_name='mission',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='logo',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='Novak Hospitality Solutions', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='subtitle',
            field=models.CharField(blank=True, default='Powering Success', max_length=200),
        ),
    ]
